[tool.black]
line-length = 120
exclude = '''
/(
    venv|
    \.venv|
    migrations
)/
'''

[tool.isort]
profile = "black"
skip = ["venv", ".venv", "migrations"]
multi_line_output = 3
force_single_line = true
