name: Lint, Test, & Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Lint
        run: make lint

      - name: Test
        run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      HOSTNAME: ${{ secrets.HOSTNAME }}
      USERNAME: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Init Ansible
        run: |
          make init-ansible

      - name: Init SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > $RUNNER_TEMP/ssh_key
          chmod 600 $RUNNER_TEMP/ssh_key

      - name: Deploy Nginx
        run: |
          ansible-playbook ansible/deploy/nginx.yaml -i "$HOSTNAME," --key-file $RUNNER_TEMP/ssh_key --user "$USERNAME"

      - name: Deploy App
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        run: |
          echo "$PRODUCTION_ENV" > $RUNNER_TEMP/production.env
          set -o allexport; source $RUNNER_TEMP/production.env; set +o allexport;
          ansible-playbook ansible/deploy/app.yaml -i "$HOSTNAME," --key-file $RUNNER_TEMP/ssh_key --user "$USERNAME" --extra-vars "$PRODUCTION_ENV"
          rm -f $RUNNER_TEMP/production.env

      - name: Remove SSH Key
        run: |
          rm -f $RUNNER_TEMP/ssh_key
